name: pre-commit
on:
  pull_request:
  push:
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: sched
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: jidicula/clang-format-action@v4.11.0
      with:
        clang-format-version: '6'
